### ISSUE TITLE
Bootstrap 

### ISSUE THREAD

**Issue by relhajja** [eminaktas/flux2-without-cni#1]
Hello, thanks for your work, can you explain how did you bootstrap flux and sync it with a github repo

**Comment by eminaktas** [comment]
Hello @riadelhajjaji-2001, I apologize for my very late response. I somehow missed your question in my emails or notifications. You may have already found the answer, but to address your question: I used the Flux CLI to bootstrap Flux. You can refer to [this documentation](https://fluxcd.io/flux/cmd/flux_bootstrap_github/) for more details. The crucial part is to define --path=./clusters/my-cluster for your repository during the bootstrap.
